server:
  port: 8081

spring:
  application:
    name: Suriname
  config:
<<<<<<< HEAD
    import: optional:file:env

=======
    import: optional:file:.env
>>>>>>> 5ab87acb4e507e130a2c2e7b1414c3acb51fc02b

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect