server:
  port: 8081

spring:
  application:
    name: Suriname
  
  # H2 인메모리 데이터베이스 설정 (데모용)
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트용으로 매번 새로 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: c3VyaW5hbWVlbWFuaXJ1c2ZpbmFscHJvamVjdDIwMjVhdWd1c3Q=
  expiration: 86400000

portone:
  hostname: https://api.portone.io/v2
  secret-key: test_sk_d26DlbXAaV0xQbpa7y1VqY50Q9RB

# SMS 및 배송 API 설정 (데모용)
sms:
  api:
    url: https://api.coolsms.co.kr/sms/4/send
    key: dummy-key
    secret: dummy-secret
  sender:
    phone: 1588-0000

courier:
  api:
    cj:
      key: dummy-key
    lotte:
      key: dummy-key