server:
  port: 8081

spring:
  application:
    name: Suriname
  config:
    import: optional:file:.env.properties
  sql:
    init:
      mode: never
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.http.client.HttpClientAutoConfiguration
      - org.springframework.boot.autoconfigure.web.client.RestClientAutoConfiguration

  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

jwt:
  secret: "${JWT_SECRET}"
  expiration: 86400000

toss:
  secret-key: "${TOSS_SECRET_KEY}"
  client-key: "${TOSS_CLIENT_KEY}"