name: Backend Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: { group: be-cd-prod, cancel-in-progress: true }

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build
        working-directory: suriname-backend
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Find JAR
        id: jar
        working-directory: suriname-backend
        run: echo "file=$(ls build/libs/*-SNAPSHOT.jar | head -n1)" >> $GITHUB_OUTPUT

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "${{ steps.jar.outputs.file }}"
          target: "${{ secrets.BACKEND_DIR }}/build/libs/"
          strip_components: 2

      - name: Restart backend service
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl daemon-reload || true
            sudo systemctl restart ${{ secrets.SERVICE_NAME }}
            sudo systemctl status ${{ secrets.SERVICE_NAME }} --no-pager -n 20 || true
