name: Frontend Deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: { group: fe-cd-prod, cancel-in-progress: true }

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: suriname-frontend/package-lock.json

      - name: Build (env 주입 + 패키징)
        working-directory: suriname-frontend
        env:
          VITE_API_URL: "/api"
          VITE_ALGOLIA_APP_ID: "5YCEBAVIOS"
          VITE_ALGOLIA_SEARCH_API_KEY: "98bc7573d3d136029642f704d1fa2e48"
        run: |
          set -euo pipefail
          npm ci || (rm -rf node_modules package-lock.json && npm install)
          npm i -D @rollup/rollup-linux-x64-gnu || true
          npm run build
          test -f dist/index.html
          test -d dist/assets
          tar -czf ../dist.tgz -C dist .

      - name: Debug dist.tgz path (Runner 내부)
        run: |
          echo "=== dist.tgz 위치 확인 ==="
          find . -name dist.tgz -exec ls -lh --time-style=long-iso {} \;

      - name: Upload dist.tgz to EC2 (/tmp)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist.tgz"
          target: "/tmp/"
          overwrite: true

      - name: Unpack → Move to Nginx root → Reload
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -euo pipefail
            ROOT_DIR=${{ secrets.FRONTEND_DIR }}
            TMP_DIR="/tmp/suriname-dist"

            echo "=== /tmp/dist.tgz 존재 여부 확인 ==="
            if [ ! -f /tmp/dist.tgz ]; then
              echo "[ERROR] dist.tgz 파일이 EC2에 없습니다."
              exit 1
            fi
            ls -lh --time-style=long-iso /tmp/dist.tgz

            # 기존 배포 폴더 삭제
            sudo rm -rf "$TMP_DIR"
            sudo mkdir -p "$TMP_DIR"

            # 압축 해제
            sudo tar -xzf /tmp/dist.tgz -C "$TMP_DIR"

            # nginx root로 복사
            sudo mkdir -p "$ROOT_DIR"
            sudo rsync -a --delete "$TMP_DIR"/ "$ROOT_DIR"/
            sudo chown -R www-data:www-data "$ROOT_DIR"

            # nginx reload
            sudo nginx -t
            sudo systemctl reload nginx
