name: Frontend Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: { group: fe-cd-prod, cancel-in-progress: true }

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: suriname-frontend/package-lock.json

      - name: Build
        working-directory: suriname-frontend
        env:
          VITE_API_URL: "/api"
          VITE_ALGOLIA_APP_ID: "5YCEBAVIOS"
          VITE_ALGOLIA_SEARCH_API_KEY: "98bc7573d3d136029642f704d1fa2e48"
        run: |
          npm ci || (rm -rf node_modules package-lock.json && npm install)
          npm run build
          ls -al dist || true

      - name: Upload dist to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "suriname-frontend/dist/**"
          target: "/tmp/suriname-dist/"

      - name: Move to Nginx root & reload
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            ROOT_DIR=${{ secrets.FRONTEND_DIR }}
            sudo mkdir -p "$ROOT_DIR"
            sudo rm -rf "$ROOT_DIR"/*
            sudo cp -r /tmp/suriname-dist/* "$ROOT_DIR"/
            sudo chown -R www-data:www-data "$ROOT_DIR"
            sudo nginx -t
            sudo systemctl reload nginx
