name: Frontend Deploy

on:
  push:
    branches: [ "main" ]
    paths:
      - "suriname-frontend/**"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: suriname-frontend/package-lock.json

      - name: Create .env file
        working-directory: suriname-frontend
        run: |
          echo "VITE_ALGOLIA_APP_ID=${{ secrets.ALGOLIA_APP_ID }}" >> .env
          echo "VITE_ALGOLIA_SEARCH_API_KEY=${{ secrets.ALGOLIA_SEARCH_API_KEY }}" >> .env
          echo "VITE_ALGOLIA_ADMIN_KEY=${{ secrets.ALGOLIA_ADMIN_KEY }}" >> .env

      - name: Install dependencies
        working-directory: suriname-frontend
        run: npm ci

      - name: Build project (Vite)
        working-directory: suriname-frontend
        run: npm run build

      - name: Archive dist
        working-directory: suriname-frontend
        run: tar -czf dist.tgz -C dist .

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Upload dist.tgz to EC2
        run: scp -o StrictHostKeyChecking=no suriname-frontend/dist.tgz ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/dist.tgz

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo rm -rf /usr/share/nginx/html/*
            sudo tar -xzf /tmp/dist.tgz -C /usr/share/nginx/html/
            sudo chown -R www-data:www-data /usr/share/nginx/html
            sudo nginx -t
            sudo systemctl reload nginx
          EOF
